# Site settings
title: Melanin Queens United
email: nshields01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  WARNING:  This site has extreme Melanin!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
# twitter_username: jek
github_username:  melaninqueensunited

# Build settings
markdown: kramdown
